### ISSUE TITLE
Encouraging SQL Injection in SQLAPI

### ISSUE THREAD

**Issue by A248** [TheDevTec/TheAPI#1]
**Describe the bug**
The [SQLAPI](https://github.com/TheDevTec/TheAPI/blob/7ea92ade8be387c3c22b78e47f4ae7ced218ac4f/src/me/DevTec/TheAPI/SQLAPI/SQLAPI.java) helper class relies on String concatenation to construct queries. Developers should always use PreparedStatements and set parameters properly. If needed, there are other external libraries designed to reduce JDBC verbosity which handle parameterisation the right way.

**Version of TheAPI**
Master on 7ea92ade8be387c3c22b78e47f4ae7ced218ac4f (the time of writing this)

**Screenshots**
n/a

**Additional context**
I thought I should warn you about this

**Comment by TheDevTec** [comment]
Hello @A248 ,
To the SQLAPI.class added methods with PreparedStatement, see https://github.com/TheDevTec/TheAPI/commit/4daa3e98ca7db1df59aabf4406fcfb7ab640f674
