### ISSUE TITLE
Request for add new feature to plugin/site

### ISSUE THREAD

**Issue by Setloth** [TheDevTec/TheAPI#5]
**Is your feature request related to plugin or site**
Site/GitHub

**Short description of feature**
Create a wiki with just what GitHub supplies. I know there are examples on the Discord, but having a more concentrated list of usages and examples as well as further context for the api would be nice to have.

**Comment by TheDevTec** [comment]
https://github.com/TheDevTec/TheAPI/wiki

I have prepared a wiki - Simple description of classes
- StraikerinaCZ

**Comment by Setloth** [comment]
thanks 😊

**Comment by Setloth** [comment]
I'll close, but I will also note that having sections for the classes & their methods would also be nice for documentation, if time permits.

**Comment by Setloth** [comment]
> https://github.com/TheDevTec/TheAPI/wiki
> 
> I have prepared a wiki - Simple description of classes
> 
> * StraikerinaCZ

I see there's another page for the enchantment api, any intention of expanding to the other classes at a further date?
