### ISSUE TITLE
StringUtils.colorize()

### ISSUE THREAD

**Issue by Setloth** [TheDevTec/TheAPI#6]
**Describe the bug**
Colorized function in the String Util class seems to fail coloring Strings
I am using it the same usage as I was prior to the latest update:
For Example:
```java
scoreboard.setTitle(Config.UI_SCOREBOARD_TITLE.getText());
```
Where `scoreboard` is `new ScoreboardAPI(player, 0);` and where the input parameter resolves to `"&eDuprs"`

**Version of TheAPI**
9.9.2

**Screenshots**
Result of above code:
![image](https://user-images.githubusercontent.com/44213317/167234854-d71e0379-b62e-40a9-9a3d-b27e7fad2154.png)
Before, it would have been colored.
I also logged the output of both the raw string, and one that passed through `StringUtils.colorize()` and it was still blank with its `&e` unstripped.

**Comment by Setloth** [comment]
I also tried sending it through Component class processing first, into a component, then back to a string with `LegacyComponentSerializer.legacySection()` to get the section (native) allocation for colors. 

I also tried using `ChatColor.translateAlternativeColorCodes('&', text);` but also to no avail as the input to the `setTitle` method.

**Comment by TheDevTec** [comment]
I did my tests on version 1.8.8 and everything works without a problem.

**Comment by TheDevTec** [comment]
```java
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.plugin.java.JavaPlugin;

import me.devtec.shared.scheduler.Scheduler;
import me.devtec.shared.scheduler.Tasker;
import me.devtec.theapi.bukkit.BukkitLoader;
import me.devtec.theapi.bukkit.scoreboard.SimpleScore;

public class Loader extends JavaPlugin implements Listener {
	int task;
	public void onEnable() {
		Bukkit.getPluginManager().registerEvents(this, this);
		
		SimpleScore score = new SimpleScore().setTitle("&eTesting title");
		
		task=new Tasker() {
			public void run() {
				for(Player online : BukkitLoader.getOnlinePlayers())
					score.addLine("").addLine("&7 > &fNickname:").addLine("&e"+online.getName()).addLine("").send(online);
			}
		}.runRepeating(10, 20); //async
	}
	
	public void onDisable() {
		Scheduler.cancelTask(task);
		for(Player online : BukkitLoader.getOnlinePlayers())
			SimpleScore.scores.remove(online.getUniqueId()).destroy();
	}
	
	@EventHandler
	public void quitEvent(PlayerQuitEvent e) {
		SimpleScore.scores.remove(e.getPlayer().getUniqueId()).destroy();
	}
}
```

**Comment by TheDevTec** [comment]
Questions:
1) What's your client version
2) Do you have installed any mods (client side)
3) Is your client modified (Lunar, Badlion.. etc)
4) Do you have installed ProtocolLib & ViaVersion (server side)
5) Do you have installed plugin on server or you are shading with your project

**Comment by Setloth** [comment]
1) 1.18.2
2) no
3) no
4) ViaVersion is installed, but server version is 1.18.2 so it makes no difference (idk why i have it installed lol)
5) TheAPI is installed on the server

I mean idk exactly what changed cause all i did was update TheAPI i didn't touch my code for it, maybe something to do with 1.18, unsure

**Comment by TheDevTec** [comment]
I think, problem is solved. Download update on the [Spigot](https://www.spigotmc.org/resources/theapi.72679/update?update=455629)

**Comment by Setloth** [comment]
> I think, problem is solved. Download update on the [Spigot](https://www.spigotmc.org/resources/theapi.72679/update?update=455629)

Alright cool, I will test it out

**Comment by Setloth** [comment]
Update: Colors seem to be fixed, but bold seems to still break coloring, unsure what specifically could be causing (could be the double max, as noted in the update).

**Comment by Straikerinos** [comment]
Okey, I found problem and solved.
Fix will be available in new spigot update.
- Thanks for using TheAPI!
